FROM apache/airflow:2.9.1-python3.11 as base
COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip 

USER root
RUN apt update
RUN apt install git -y

USER airflow
RUN pip install -r /requirements.txt --no-cache-dir

